__author__ = 'dchekhonin'

email  = 'feanor3535@gmail.com'
password = 'Wizard2626'
assert_homepage_item = 'Elvis'
assert_sentmailpage_item = '#sent'
main_email_site = 'http://mail.google.com'
empty_email = ''
empty_password = ''
incorrect_email = 'feanor353555@gmail.com'
incorrect_password = 'qwerty'
assert_empty_email_error = 'Please enter your email.'
assert_incorrect_email_error = 'Sorry, Google doesn\'t recognize that email'
assert_empty_password_error = 'Please enter your password'
assert_incorrect_password_error = 'The email and password you entered don\'t match'
